port: 5000
api: {
    url: https://publish-api.development.digital-land.info,
    port: 8082,
    validationEndpoint: /api/dataset/validate/file/request
}
maintenance: {
    serviceUnavailable: true,
    upTime: "9am on Monday 19 November 2024"
}
