port: 3000
maintenance: {
    serviceUnavailable: false,
    upTime: "9am on Monday 19 November 2024"
}
redis: false
url: ''
serviceName: 'Endpoint Submission Form'
feedbackLink: '#'
jira: {
    customFieldMappings: {
        'customfield_10000': 'emails'
    }
}