port: 5000
api: {
    url: http://127.0.0.1:8082,
    port: 8082,
    validationEndpoint: /api/dataset/validate/file/request
}
maintenance: {
    serviceUnavailable: false,
    upTime: "9am on Monday 19 November 2024"
}
serviceName: 'Publish planning and housing data for England'
feedbackLink: '#'