asyncRequestApi: {
    url: http://development-pub-async-api-lb-2117113766.eu-west-2.elb.amazonaws.com
}
aws: {
    region: eu-west-2,
    bucket: 'development-pub-async-request-files',
}
url: 'https://publish.development.digital-land.info/'
